EMBED_MODEL = "nomic-embed-text"

OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_EMBEDDING_URL = "http://localhost:11434/api/embeddings"
MODEL = "mistral"

LLM_TIMEOUT = 300
EMBEDDING_TIMEOUT = 120

MAX_RETRIES = 3
RETRY_BASE_WAIT = 1.0
RETRY_BACKOFF_FACTOR = 2.0

INDEXING_MAX_WORKERS = 4

PARENT_CHUNK_SIZE = 1800
PARENT_OVERLAP = 200

CHILD_CHUNK_SIZE = 600
CHILD_OVERLAP = 80

MAX_CONTEXT_CHARS = 4000

TOP_K = 10